# smart plug .yaml

substitutions:
  area: "jasmine"
  node_id: "jasmine-oil-heater"
  friendly_name: "Oil Heater Plug"

  relay_id: "${node_id}"
  relay_name: "${friendly_name}"

<<: !include common.yaml
