# smart plug .yaml

substitutions:
  area: "lounge"
  node_id: "lounge-wall-heater"
  friendly_name: "Wall Heater Plug"

  relay_id: "${node_id}"
  relay_name: "${friendly_name}"

<<: !include common.yaml
